name: 'version'

inputs:
  path:
    required: true
    type: string
  project:
    required: true
    type: string

outputs:
  version:
    description: "The generated package version"
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install MinVer
      run: dotnet tool install --global minver-cli --version 6.0.0
      shell: pwsh

    - name: set version
      id: set-version
      shell: pwsh
      run: |
        $version = ""
        $csprojFile = "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.csproj"

        [xml]$csprojContent = Get-Content -Path $csprojFile
        foreach ($propertyGroup in $csprojContent.Project.PropertyGroup) {
            if ($propertyGroup.MinVerTagPrefix) {
            $version = minver --verbosity error -t $($propertyGroup.MinVerTagPrefix) -p ci
            break
            }
        }

        Write-Host "Version: $version"
        if($version -eq "") {
            Write-Error "Version not found"
            exit 1
        }
        echo "version=${version}" >> $env:GITHUB_OUTPUT   
       

       
   