name: 'Deploy Packages'

permissions:
  id-token: write
  contents: read

inputs:
  directory:
    required: true
    type: string  
  storageAccountName:
    required: true
    type: string  
  tenantId:
    required: true
    type: string
  subscriptionId:
    required: true
    type: string
  clientId:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.clientId }}
        tenant-id: ${{ inputs.tenantId }}
        subscription-id: ${{ inputs.subscriptionId }}

    - name: Azure CLI script
      uses: azure/cli@v2
      env:
        STORAGE_ACCOUNT: ${{ inputs.storageAccountName }}
        DIRECTORY: ${{ inputs.directory }}
        
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch --account-name "$STORAGE_ACCOUNT" --auth-mode login -d "packages" --destination-path "$TARGET" -s "$DIRECTORY" --pattern "*.zip*"
        