parameters:
- name: config
  type: string
  default: debug
- name: projects
  type: object

stages:
- stage: Deploy

  jobs:
  - job: Deploy

    strategy:
      matrix:
        win-x64:
          vmImage: windows-latest
          target: win-x64

        win-x86:
          vmImage: windows-latest
          target: win-x86

        linux-x64:
          vmImage: ubuntu-latest
          target: linux-x64

        osx-x64:
          vmImage: macos-latest
          target: osx-x64

    pool:
      vmImage: $(vmImage)

    steps:
    - template: ../restore.yml
      parameters:
        config: ${{ parameters.config }}

    - ${{ each project in parameters.projects }}:
      - pwsh: dotnet publish ${{ project }} -c ${{ parameters.config }} -o $(Build.ArtifactStagingDirectory)/drop-$(target) -r $(target) -f net6.0 --self-contained true -p:EnableCompressionInSingleFile=true
        displayName: Publish

    - publish: $(Build.ArtifactStagingDirectory)/drop-$(target)
      artifact: drop-$(target)
