parameters:
- name: stages
  type: stageList

- name: targets
  type: object
  default:
  - win-x64
  - win-x86
  - linux-x64
  - osx-x64

stages:
- ${{ each stage in parameters.stages }}:
  - ${{ each pair in stage }}:
      ${{ pair.key }}: ${{ pair.value }}

    environment: ${{ stage.templateContext.environment }}
    
    jobs:
    - ${{ each target in parameters.targets }}:
      - deployment: Release_${{ target }}

        pool:
          vmImage: windows-latest

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: package-${{ target }}
                  displayName: Download artifacts

                - pwsh: get-childitem "$(Pipeline.Workspace)/package-${{ target }}/*" | foreach { rename-item $_ $_.Name.Replace("fiskaltrust.Launcher-", "") }
                  displayName: Rename artifacts

                - task: AzureCLI@2
                  displayName: Publish to blob storage
                  inputs:
                    azureSubscription: ${{ stage.templateContext.environment }}
                    scriptType: ps
                    scriptLocation: inlineScript
                    inlineScript: |
                      az storage blob upload-batch --account-name ${{ stage.templateContext.storage }} -d "packages" --destination-path "${{ target }}/fiskaltrust.Launcher/" -s "$(Pipeline.Workspace)/package-${{ target }}/" --pattern "*.zip*"