stages:
- stage: Test

  pool:
    vmImage: windows-latest

  jobs:
  - job: Test

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build
      displayName: Build
  
    - pwsh: dotnet test
      displayName: Test

    - pwsh: ls -Depth 8 | select fullname | where { $_.fullname.conatins("log_") }
      condition: always()
