parameters:
- name: config
  type: string
  default: debug

stages:
- stage: Test

  jobs:
  - job: TestWindows
    pool:
      vmImage: windows-latest
    
    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }} --logger "consoletrxconsole;verbosity=detailed"
      displayName: Test

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunTitle: Windows Tests
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

  - job: TestLinux
    pool:
      vmImage: ubuntu-latest

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }} --logger trx
      displayName: Test

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunTitle: Linux Tests
        testRunner: VSTest
        testResultsFiles: '**/*.trx'

  - job: TestMacOS
    pool:
      vmImage: macos-latest

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }} --logger trx
      displayName: Test

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunTitle: MacOS Tests
        testRunner: VSTest
        testResultsFiles: '**/*.trx'