stages:
- stage: Test

  pool:
    vmImage: windows-latest

  jobs:
  - job: Test

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build
      displayName: Build
  
    - pwsh: dotnet test
      displayName: Test

    - pwsh: ls -Depth 2 test\fiskaltrust.Launcher.IntegrationTest\bin\Debug\net6.0 | select fullname
      condition: always()
