parameters:
- name: config
  type: string
  default: debug

stages:
- stage: Test

  jobs:
  - job: TestWindows
    pool:
      vmImage: windows-latest
    
    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }}
      displayName: Test

  - job: TestLinux
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 6.0.x

    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }}
      displayName: Test

  - job: TestMacOS
    pool:
      vmImage: macos-latest

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }}
      displayName: Test