stages:
- stage: Test

  pool:
    vmImage: windows-latest

  jobs:
  - job: Test

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build
      displayName: Build
  
    - pwsh: dotnet test
      displayName: Test
