parameters:
- name: config
  type: string
  default: debug

stages:
- stage: Test

  pool:
    vmImage: windows-latest

  jobs:
  - job: Test

    steps:
    - template: ../restore.yml

    - pwsh: dotnet build -c ${{ parameters.config }}
      displayName: Build
  
    - pwsh: dotnet test -c ${{ parameters.config }}
      displayName: Test
