name: Package Launcher

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches:
      - main
  # workflow_run:
  #   workflows: ["Test Launcher"]
  #   types:
  #     - completed

jobs:
  # test-launcher:
  #     uses: ./.github/workflows/test.yml   
  #     permissions:
  #      checks: write
  #      pull-requests: write

  package:
    # needs: [test-launcher]
    name: package
    strategy:
      matrix:
        include:
          - vmImage: windows-latest
            target: win-x64
            scriptFolder: 'windows'

          - vmImage: windows-latest
            target: win-x86
            scriptFolder: 'windows'

          - vmImage: ubuntu-latest
            target: linux-x64
            scriptFolder: 'linux'

          - vmImage: ubuntu-latest
            target: linux-arm
            scriptFolder: 'linux'

          - vmImage: ubuntu-latest
            target: linux-arm64
            scriptFolder: 'linux'

          - vmImage: macos-latest
            target: osx-x64
            scriptFolder: 'macos'
   
    runs-on: ${{ matrix.vmImage }}

    steps:
      - uses: actions/checkout@v4  
       
      - name: Set build configuration
        id: set-config
        shell: bash
        run: |
         echo "GITHUB_REF=${GITHUB_REF}"
         if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          echo "config=Release" >> $GITHUB_OUTPUT
         else
          echo "config=Debug" >> $GITHUB_OUTPUT
         fi

      # - uses: fiskaltrust/middleware/.github/actions/build@main
      #   with:
      #     pattern: fiskaltrust.Launcher.sln
      #     configuration: ${{ steps.set-config.outputs.config }}

      # - name: Publish ${{ matrix.project }}
      #   shell: pwsh
      #   run: |
      #     mv ./Directory.build.props ./Directory.Build.props
      #     dotnet publish ./src/${{ matrix.project }}/${{ matrix.project }}.csproj -c ${{ needs.test.outputs.config }} -o $(Build.ArtifactStagingDirectory)/drop-$(target) -r $(target) -f net8.0 --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:GenerateRuntimeConfigurationFiles=false -p:PublishSingleFile=true
      
      # - uses: fiskaltrust/middleware/.github/actions/sign@main
      #   with:
      #     certificate: 'codesigning.pfx'
      #     password: '$(Code_Signing_Password)'
      #     path: src
    
      - name: Copy executables
        shell: pwsh
        id: copy-executables
        run: |
           $project1 = "fiskaltrust.Launcher"
           $project2 = "fiskaltrust.LauncherUpdater"
           $path = "./publish/raw-${{ matrix.target }}/"
           $target = "${{ matrix.target }}"

           echo "path=$path" >> $env:GITHUB_OUTPUT
           New-Item -ItemType Directory -Force -Path ./publish/raw-${{ matrix.target }}

           dotnet publish src/$project1/$project1.csproj --configuration  ${{ steps.set-config.outputs.config }} -f net8.0 --output ./publish/drop-${{ matrix.target }} -r ${{ matrix.target }} --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:GenerateRuntimeConfigurationFiles=false -p:PublishSingleFile=true
           dotnet publish src/$project2/$project2.csproj --configuration  ${{ steps.set-config.outputs.config }} -f net8.0 --output ./publish/drop-${{ matrix.target }} -r ${{ matrix.target }} --self-contained true -p:DebugType=None -p:DebugSymbols=false -p:GenerateRuntimeConfigurationFiles=false -p:PublishSingleFile=true
           Get-ChildItem -Path "./publish/drop-$target/${project1}*" -File | Where-Object { $_.Extension -ne ".json" } | Move-Item -Destination $path
          
      - uses: ./.github/actions/version
        id: set-version
        with:
          project: fiskaltrust.Launcher
          path: src          

      - uses: ./.github/actions/zip
        with:
          path: ${{ steps.copy-executables.outputs.path }}
          zipFileName : "fiskaltrust.Launcher-${{ steps.set-version.outputs.version }}"
          artifactName: "package-${{ matrix.target }}"


      # - uses: ./.github/actions/package
      #   with:
      #     project: fiskaltrust.Launcher,fiskaltrust.LauncherUpdater
      #     path: src
      #     target : ${{ matrix.target }} 