name: Release Launcher

on:
  workflow_dispatch:
  push:
    branches:
      - refs/tags/*
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read

jobs:
  package:
    uses: ./.github/workflows/package.yml 
  release:
    needs: [package]
    strategy:
      matrix:
        include:
          - vmImage: windows-latest
            target: win-x64
            scriptFolder: "windows"

          - vmImage: windows-latest
            target: win-x86
            scriptFolder: "windows"

          - vmImage: ubuntu-latest
            target: linux-x64
            scriptFolder: "linux"

          - vmImage: ubuntu-latest
            target: linux-arm
            scriptFolder: "linux"

          - vmImage: ubuntu-latest
            target: linux-arm64
            scriptFolder: "linux"

          - vmImage: macos-latest
            target: osx-x64
            scriptFolder: "macos"

    runs-on: ${{ matrix.vmImage }}

    steps:
      - uses: actions/checkout@v4   
      - uses: ./.github/workflows/package.yml
        with:
          environment: Sandbox
          target: ${{ matrix.target }}
     

