stages:
- stage: Build
  pool:
    vmImage: windows-latest
  jobs:
  - job: Build
    steps:
    - task: yavt@1
      inputs:
        pathToVersionJson: version.json
        semverVersion: v1 # still needed?

    - task: UseDotNet@2
      inputs:
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        ${{ if startsWith(variables.Build.SourceBranch, 'refs/tags/v') }}: 
          vstsFeed: release
        ${{ else }}:
          vstsFeed: dev

    - task: DotNetCoreCLI@2
      inputs:
        command: build
