parameters:
- name: reason
  type: string
  values:
  - pr
  - release
  - main

pool:
  vmImage: windows-latest

jobs:
- job: Build
  steps:
  - task: yavt@1
    inputs:
      pathToVersionJson: version.json
      semverVersion: v1 # still needed?

  - task: UseDotNet@2
    inputs:
      version: '6.0.x'

  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      ${{ if eq(parameters.reason, 'release') }}: 
        vstsFeed: release
      ${{ else }}:
        vstsFeed: dev

  - task: DotNetCoreCLI@2
    inputs:
      command: build
