stages:
- stage: Build
  pool:
    vmImage: windows-latest
  jobs:
  - job: Build
    steps:
    - task: yavt@1
      inputs:
        pathToVersionJson: version.json
        semverVersion: v1 # still needed?

    - task: UseDotNet@2
      inputs:
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      displayName: ${{ variables.Build.SourceBranch }}
      inputs:
        command: restore
        ${{ if startsWith(variables.Build.SourceBranch, 'refs/tags/v') }}: 
          vstsFeed: release
        ${{ else }}:
          vstsFeed: dev

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: --configuration release

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '-o $(Build.ArtifactStagingDirectory)/drop'
        modifyOutputPath: true
    
    - publish: $(Build.ArtifactStagingDirectory)/drop
      artifact: drop
