stages:
- stage: Deploy
  jobs:
  - job: Deploy
    strategy:
    matrix:
      win-x64:
        vmImage: 'windows-latest'
        target: win-x64
      win-x86:
        vmImage: 'windows-latest'
        target: win-x86
      linux-x64:
        vmImage: 'ubuntu-latest'
        target: linux-x64
      osx-x64:
        vmImage: 'macos-latest'
        target: osx-x64
    pool:
      vmImage: $(vmImage)
    steps:
    - task: yavt@1
      inputs:
        pathToVersionJson: version.json
        semverVersion: v1 # still needed?

    - task: UseDotNet@2
      inputs:
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      displayName: ${{ variables.Build.SourceBranch }}
      inputs:
        command: restore
        ${{ if startsWith(variables.Build.SourceBranch, 'refs/tags/v') }}: 
          vstsFeed: release
        ${{ else }}:
          vstsFeed: dev

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: --configuration release

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '-o $(Build.ArtifactStagingDirectory)/drop-$(target)'
        modifyOutputPath: true
    
    - publish: $(Build.ArtifactStagingDirectory)/drop-$(target)
      artifact: drop
