parameters:
- name: branch
  type: string
  default: $(Build.SourceBranch)

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    strategy:
      matrix:
        win-x64:
          vmImage: windows-latest
          target: win-x64
        win-x86:
          vmImage: windows-latest
          target: win-x86
        linux-x64:
          vmImage: ubuntu-latest
          target: linux-x64
        osx-x64:
          vmImage: macos-latest
          target: osx-x64
    pool:
      vmImage: $(vmImage)
    steps:
    - task: yavt@1
      inputs:
        pathToVersionJson: version.json
        semverVersion: v1 # still needed?

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 5.x

    - task: NuGetAuthenticate@0
      inputs:
        nuGetServiceConnections: release-feed

    - pwsh: dotnet restore
      displayName: Restore

    - pwsh: dotnet build -c release
      displayName: Build

    - pwsh: dotnet build -c release -o $(Build.ArtifactStagingDirectory)/drop-$(target) -r $(target) -f net6.0
      displayName: Publish

    - publish: $(Build.ArtifactStagingDirectory)/drop-$(target)
      artifact: drop-$(target)
