steps:
- task: yavt@1
  inputs:
    pathToVersionJson: version.json
    addCiLabel: true
    failOnTagVersionMismatch : true

- task: UseDotNet@2
  inputs:
    packageType: sdk
    useGlobalJson: true
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetAuthenticate@0

- pwsh: dotnet restore
  displayName: Restore
