steps:
- task: yavt@1
  inputs:
    pathToVersionJson: version.json
    addCiLabel: true

- task: UseDotNet@2
  inputs:
    version: 7.0.x

- task: NuGetAuthenticate@0

- pwsh: dotnet restore
  displayName: Restore
