parameters:
- name: branch
  type: string
  default: $(Build.SourceBranch)

stages:
- stage: Test
  pool:
    vmImage: windows-latest
  jobs:
  - job: Test
    steps:
    - task: yavt@1
      inputs:
        pathToVersionJson: version.json
        semverVersion: v1 # still needed?

    - task: UseDotNet@2
      inputs:
        version: 6.0.x

    - task: NuGetAuthenticate@0
      inputs:
        nuGetServiceConnections: release-feed

    - pwsh: dotnet restore
      displayName: Restore

    - pwsh: dotnet build -c release
      displayName: Test
