trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/*

variables:
  branch: $(Build.SourceBranch)

stages:
  - template: templates/stages/test.yml
    parameters:
      ${{ if startsWith(variables.branch, 'refs/tags/v')}}:
        config: release
      ${{ else }}:
        config: debug

  - template: templates/stages/build.yml
    parameters:
      projects:
        - fiskaltrust.Launcher
        - fiskaltrust.LauncherUpdater
      ${{ if startsWith(variables.branch, 'refs/tags/v')}}:
        config: release
      ${{ else }}:
        config: debug

  - template: templates/stages/release.yml
    parameters:
      stages:
        - stage: Release_Sandbox
          dependsOn: Build
          templateContext:
            storage: stdevwesteuropepackages
            environment: rg-dev-westeurope-packages

        # - stage: Release_Production
        #   dependsOn: Release-Sandbox
        # condition: startsWith(variables.branch, 'refs/tags/v')
        #   templateContext:
        #     env: production
        #     storage: stwesteuropepackages
        #     serviceConnection: rg-westeurope-packages
