resources:
  pipelines:
    - pipeline: build
      source: fiskaltrust.Launcher
      trigger:
        branches:
          include:
            - refs/tags/v*

trigger: none
pr: none

stages:
  - template: templates/stages/release.yml
    parameters:
      artifact: build
      stages:
        - stage: Release_Sandbox
          templateContext:
            environment: sandbox
            storage: stdevwesteuropepackages
            serviceConnection: rg-dev-westeurope-packages

        - stage: Release_Production
          dependsOn: Release_Sandbox
          templateContext:
            environment: production
            storage: stprodwesteuropepackages
            serviceConnection: rg-prod-westeurope-packages

  - template: templates/stages/github-release.yml
    parameters:
      dependsOn: Release_Production
      artifact: build
      serviceConnection: fiskaltrust-github
      repositoryName: fiskaltrust/middleware-launcher

  - template: templates/deb/release.yml
    parameters:
      artifact: build
      serviceConnection: ft-acp-csp-austria-production
      storage: fta102downloads
