trigger:
  batch: true
  branches:
    include:
      - main
      - refs/tags/*

variables:
  branch: $(Build.SourceBranch)

stages:
  - template: templates/stages/test.yml
    parameters:
      ${{ if startsWith(variables.branch, 'refs/tags/v')}}:
        config: Release
      ${{ else }}:
        config: Debug

  - template: templates/stages/build.yml
    parameters:
      projects:
        - fiskaltrust.Launcher
        - fiskaltrust.LauncherUpdater
      ${{ if startsWith(variables.branch, 'refs/tags/v')}}:
        config: Release
      ${{ else }}:
        config: Debug

  - template: templates/deb/build.yml
